In [1]:
import numpy as np # SHIFT + ENTER

$x = \begin{bmatrix}x_1 \\ x_2 \\ x_3\end{bmatrix}$

In [3]:
x1 = 3
x2 = 55
x3 = -2.4

x = np.array([x1, x2, x3])

x

array([ 3. , 55. , -2.4])

$X = \begin{bmatrix}x_{11} & x_{12} \\ x_{21} & x_{22}\end{bmatrix}$

In [5]:
x_11 = 3
x_12 = 6
x_21 = 7
x_22 = -67
X = np.array([[x_11, x_12],[x_21, x_22]])

X

array([[  3,   6],
       [  7, -67]])

In [7]:
print(X[0,0], X[1,1])

3 -67


In [8]:
X.T

array([[  3,   7],
       [  6, -67]])

In [9]:
print(x)
print(x.T)

[ 3.  55.  -2.4]
[ 3.  55.  -2.4]


In [10]:
y = np.array([10, 20, 30])
x + y

array([13. , 75. , 27.6])

In [11]:
x - y

array([ -7. ,  35. , -32.4])

In [12]:
c = 4
c * x

array([ 12. , 220. ,  -9.6])

$x \cdot y = x^Ty = \begin{bmatrix}x_1 & x_2 & x_3\end{bmatrix} \begin{bmatrix}y_1 \\ y_2 \\ y_3 \end{bmatrix} = x_1y_1 + x_2y_2 + x_3y_3 = \sum_{i=1}^3x_iy_i = c = c^T = (x^Ty)^T = y^Tx = y\cdot x$

In [13]:
c = x.dot(y)
print(c)

1058.0


# The norm of an object inform us on how "big" is the object

This is how we denote the norm of $x$ $||x||$

The Euclidean norm is also known as the 2-norm

$x\in\mathbb{R}^n, \quad, ||x||_2 = \sqrt{\sum_{i=1}^nx_ix_i} = \sqrt{x\cdot x} = \sqrt{x^Tx}$

$x\in\mathbb{R}^n, \quad, ||x||_1 = {\sum_{i=1}^n|x_i|}$

$||x||_2^2 = x^Tx$

In [18]:
x = np.array([1,1])
square_norm_x = x.dot(x)
print(square_norm_x)
norm_x = np.sqrt(x.dot(x))
print(norm_x)
print(x)

2
1.4142135623730951
[1 1]


In [21]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[3, 5],[-3, 4]])

print(A+B)

print(A*B) # Element-wise product or Hadamard product

print(A.dot(B)) # Standar Matrix multiplication

print(A.dot(B).dot(A)) # First it does C = AB, and then D = CA

[[4 7]
 [0 8]]
[[ 3 10]
 [-9 16]]
[[-3 13]
 [-3 31]]


Derivative of $f(x)$ we are going to represent it by $f'(x)$

$f(x,y) := x^2 + y^2, x,y\in\mathbb{R}$, $f(x,y) : \mathbb{R} \times \mathbb{R} \to \mathbb{R}$

The gradient of $f$ is represented by $\nabla f(x,y) = \begin{bmatrix}\frac{\partial f(x,y)}{\partial x} \\ \frac{\partial f(x,y)}{\partial y} \end{bmatrix}$