In [43]:
import numpy

def fitness_function(population, chromosomes):
    fit = numpy.empty(chromosomes)
    for i in range(chromosomes):
        fit[i] = - (population[i, 0]*population[i, 0] + population[i, 1]*population[i, 1])
        
    return fit
        
# Parameter initialization 
genes = 2
chromosomes = 10
mattingPoolSize = 6
offspringSize = chromosomes - mattingPoolSize
lb = -5
ub = 5
populationSize = (chromosomes, genes)
generations = 30

#Population initialization
population = numpy.random.uniform(lb, ub, populationSize)

for generation in range(generations):
    print(("Generation:", generation+1))
    #fitness = numpy.sum(population*population, axis=1)
    fitness = fitness_function(population, chromosomes)
    print("\n population")
    print(population)
    print("\n fitness calculation")
    print(fitness)
    # Following statement will create an empty two dimensional array to store parents
    parents = numpy.empty((mattingPoolSize, population.shape[1]))

    # A loop to extract one parent in each iteration
    for p in range(mattingPoolSize):
        # Finding index of fittest chromosome in the population
        fittestIndex = numpy.where(fitness == numpy.nanmax(fitness))
        # Extracting index of fittest chromosome
        fittestIndex = fittestIndex[0][0]
        # Copying fittest chromosome into parents array
        parents[p, :] = population[fittestIndex, :]
        # Changing fitness of fittest chromosome to avoid reselection of that chromosome 
        fitness[fittestIndex] = numpy.NaN
    print("\n Parents:")
    print(parents)

    # Following statement will create an empty two dimensional array to store offspring
    offspring = numpy.empty((offspringSize, population.shape[1]))
    for k in range(offspringSize):
         #Determining the crossover point
         crossoverPoint = numpy.random.randint(0,genes) 

         # Index of the first parent.
         parent1Index = k%parents.shape[0]

         # Index of the second.
         parent2Index = (k+1)%parents.shape[0]

         # Extracting first half of the offspring
         offspring[k, 0: crossoverPoint] = parents[parent1Index, 0: crossoverPoint]

         # Extracting second half of the offspring
         offspring[k, crossoverPoint:] = parents[parent2Index, crossoverPoint:]
    print("\n Offspring after crossover:")
    print(offspring)

    # Implementation of random initialization mutation. 
    for index in range(offspring.shape[0]):
        if(numpy.random.uniform(0,1,1)>0.9):
          randomIndex = numpy.random.randint(1,genes)
          randomValue = numpy.random.uniform(lb, ub, 1)
          offspring [index, randomIndex] = offspring [index, randomIndex] + randomValue
    print("\n Offspring after Mutation")
    print(offspring)

    population[0:parents.shape[0], :] = parents
    population[parents.shape[0]:, :] = offspring
    print("\nNew Population for next generation:")
    print(population)

#fitness = numpy.sum(population*population, axis=1)
fitness = fitness_function(population, chromosomes)
fittestIndex = numpy.where(fitness == numpy.max(fitness))
# Extracting index of fittest chromosome
fittestIndex = fittestIndex[0][0]
# Getting Best chromosome
fittestInd = population[fittestIndex, :]
bestFitness = fitness[fittestIndex]
print("\nBest Individual:")
print(fittestInd)
print("\nBest Individual's Fitness:")
print(bestFitness)

('Generation:', 1)

 population
[[ 0.05062076 -3.53975786]
 [-0.16561166  4.86705289]
 [ 4.52640477 -2.74027512]
 [-1.09738989 -4.90203323]
 [ 4.38036121  1.84156962]
 [-1.97366768  0.01387744]
 [-4.27301971 -2.34304369]
 [-3.74405561 -4.87712383]
 [-0.19268215  2.72219055]
 [-4.12188009  0.42208444]]

 fitness calculation
[-12.53244814 -23.71563101 -27.99744783 -25.23419437 -22.57894295
  -3.8955567  -23.74855116 -37.80428928  -7.44744782 -17.16805075]

 Parents:
[[-1.97366768  0.01387744]
 [-0.19268215  2.72219055]
 [ 0.05062076 -3.53975786]
 [-4.12188009  0.42208444]
 [ 4.38036121  1.84156962]
 [-0.16561166  4.86705289]]

 Offspring after crossover:
[[-0.19268215  2.72219055]
 [ 0.05062076 -3.53975786]
 [-4.12188009  0.42208444]
 [-4.12188009  1.84156962]]

 Offspring after Mutation
[[-0.19268215 -1.27436095]
 [ 0.05062076 -3.53975786]
 [-4.12188009  3.74148343]
 [-4.12188009  1.84156962]]

New Population for next generation:
[[-1.97366768  0.01387744]
 [-0.19268215  2.72219055]
 [ 

# Find the maximum of the following function
$f(x_1,x_2,x_3,x_4) = -(x_1^2 + x_2^2 - 0.2x_1x_2 + 0.1x_4x_1 + x_3^2 + 10x_4^2)$